apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: app3
  name: app3
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: app3
  template: 
    metadata: 
      labels: 
        app: app3
    spec: 
      containers: 
        - 
          image: vilchesplus/flask-notifier
          name: app3
          ports: 
            - 
              containerPort: 5002
