--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: selenium
  name: selenium
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: selenium
  template: 
    metadata: 
      labels: 
        app: selenium
    spec: 
      containers: 
        - 
          env: 
            - 
              name: SE_NODE_MAX_SESSIONS
              value: "50"
            - 
              name: SE_NODE_SESSION_TIMEOUT
              value: "1000"
          image: selenium/standalone-chrome
          name: selenium
          ports: 
            - 
              containerPort: 4444