apiVersion: v1
kind: Service
metadata:
  name: app3
  labels:
    run: app3
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
    name: http
  selector:
    run: app3
  type: NodePort  