apiVersion: v1
kind: Service
metadata:
  name: app4
  labels:
    run: app4
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
    name: http
  selector:
    run: app4
  type: NodePort  