apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: app4
  name: app4
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: app4
  template: 
    metadata: 
      labels: 
        app: app4
    spec: 
      containers: 
        - 
          image: vilchesplus/webscraper-flask
          name: app4
          ports: 
            - 
              containerPort: 5001
